---
# Source: ui/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: ui-0.1.0
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  name: test
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: test
  type: NodePort
---
# Source: ui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    helm.sh/chart: ui-0.1.0
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ui
      app.kubernetes.io/instance: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ui
        app.kubernetes.io/instance: test
    spec:
      containers:
        - name: react-ui
          image: "pteke20/react-ui:v1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
